bitwalker/exrm

- lib/exrm/utils.ex
- lib/mix/tasks/release.ex
- lib/mix/tasks/release.plugins.ex
We run `mix release` in our CI flow.
> Make tasks that fail exit with exit status 1.

- priv/rel/files/boot
When a release is first started as root, subsequent booting as normal user fail silently. This happens due to permission issue on `log` and `/tmp/erl_pipes/appname` folders.
resolves https://github.com/bitwalker/exrm/issues/70
> Don't fail silently when unable to write to folder

- lib/exrm/utils.ex
- test/utils_test.exs
See #110 
Fallback for non-semver versions is in place which uses regular string comparison.
One test is not running for me locally but also not on local master branch, so that one seems unrelated.
> Add semver version compare

- lib/exrm/config.ex
- lib/exrm/plugin.ex
- lib/exrm/plugins/conform.ex
- lib/exrm/plugins/consolidation.ex
- lib/mix/tasks/release.ex
The `ReleaseManager.Plugin` behaviour was missing the `defcallback` for `after_cleanup/1`. This pull request simply adds that so that the compiler will give a warning for a plugin that does not have that implemented.
> Added defcallback for after_cleanup/1 in the ReleaseManager.Plugin behaviour

- priv/rel/files/boot
- test/utils_test.exs
This change allows running a release without an included ERTS version to use any Erlang version on the target host, not only the one used to build the release.
> Detect local ERTS version automatically

- priv/rel/files/boot
Currently I can create a release using `mix release` and start the generated release,
but unfortunately upgrade and a few other options are not correctly working.
To reproduce:
```sh
$ git clone https://github.com/bitwalker/exrm-test.git && cd exrm-test
...
$ mix deps.get && mix release
...
$ cd rel/test
$ ./bin/test start
$ ./bin/test upgrade "0.0.1" # This should output "Release 0.0.1 is already installed, and set permanent.", but nothing printed.
$ echo $?
1
```
I'm using elixir 1.0.4 and exrm 0.17.1 (as I tested with [this version](https://github.com/bitwalker/exrm-test/commit/114afb76a83a6329b5ca416d720e5a5f48adf408) of [exrm-test`](https://github.com/bitwalker/exrm-test)).
The problem is due to a mismatch in the arguments passed to `bin/install_upgrade.escript` in `bin/test`.
On the …
> Catch up with relx's change in install_upgrade.escript

- lib/mix/tasks/release.ex
If I have a running server and try to make a release, it fails with an error, since function
```
:ok = :erl_tar.create()
```
does not recognize the format of pipes. And they should also not be there. 
The error that this fixes is the following:
```
mix stdout: ==> Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Performing protocol consolidation...
==> Generating release...
==> Generated .appup for elixir_stream 0.0.1 -> 0.0.2
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax …
```
> Fixing the issue of a running server pipes in /tmp directory

- lib/exrm/utils.ex
- lib/mix/tasks/release.ex
- test/utils_test.exs
This change fixes & simplifies calculating Elixir lib path using the path to Mix's beam file as a reference point. Works with both normal pkg install and also version managers.
Most version managers use shims, which makes the `ReleaseManager.Utils.get_real_path/1` point to `~/.asdf/shims/elixir`. This results in the elixir lib path being assumed as `~/.asdf/shims/elixir/lib`, which is non-existent, which is written to `relx.config`. And exrm/relx errors out when making a release while searching for iex in that path.
Tested this change with Erlang 18.0 & Elixir 1.0.5 on:
* [asdf](http://github.com/HashNuke/asdf) version manager on OS X El Capitan
* Erlang Solutions Elixir package on Ubuntu 14.04 on Vagrant (screenshot attached)
Thanks to @tsloughter for helping out.
@bitwalker please let …
> Fix Elixir lib path detection when using version managers

- priv/rel/files/boot
I was using foreground in production to run with upstart and noticed a bit of contention and it turns out my code was constantly hitting the code server for protocols. This makes Foreground start the same way as start/console.
> Pass similar args to foreground as to console/start

- priv/rel/files/boot
Remove the use of the `local` operator, which is Bash specific and not
available in the Solaris version of `/bin/sh`.
To preserve the identifying fact that these are local variables, prefix
with a double underscore.
Changes inspired by
erlware/relx@cf5ed973dbfadd5edcc1d7d9e7ddcfcc202769df
> Update boot script to be compatible with Solaris

- priv/rel/files/boot
When I trying to pass some opts to erl, I found ERL_OPTS not used in the script under Linux:
~~~bash
$ MIX_ENV=prod mix release --erl="+P 5000000 -smp enable"
$ ag ERL_OPTS rel/server/releases/0.0.1/server.sh
13:ERL_OPTS="+P 5000000 -smp enable"
~~~
> $ERL_OPTS defined but not used in priv/rel/files/boot

- priv/rel/files/boot
The current code assumes that 
```
kill -0 ""
```
is answered with an error code, which happens with the core util's kill.
Although the application stopped accordingly, the above assumption 
lead to indefinite waiting on a machine using busybox.
> add testing against empty PID in boot scrip

- priv/rel/files/boot
context: boot-script (priv/rel/files/boot)
currently  `generate_config()` copies the `$RELEASE_CONFIG_FILE` to `$GENERATED_CONFIG_DIR` and then runs `conform` on it to create `$GENERATED_CONFIG_DIR/sys.config`.
The problem: `generate_config()` does not copy `$RELEASE_CONFIG_FILE` if the target already exists. This causes configuration changes not being picked up after the first boot.
This MR changes the behavior to **always** copy the `$RELEASE_CONFIG_FILE` before running `conform`.
(The above is also true when `$RELEASE_CONFIG_FILE` is not set; in which case `$RELEASE_CONFIG_DIR/$REL_NAME.conf` is used as the source for (not) copying.)
> always copy release-config to running-config

- priv/rel/files/boot
This PR is related to [exrm_reload](https://github.com/xerions/exrm_reload) and restores order with the conform options at runtime. 
Before these changes we can change config file which placed only in `__running_config` directory because here was:
```
cp "$__conform_file" "$__running_conf"
__conform_file="$__running_conf"
```
And we were setting `CONFORM_OPTS` after this.
> Add running_conf to init arguments

- lib/exrm/plugin.ex
- lib/exrm/plugins/consolidation.ex
- lib/exrm/utils/utils.ex
- lib/mix/tasks/release.clean.ex
- lib/mix/tasks/release.ex
- test/fixtures/example_app/config/explicit_config.exs
- test/utils_test.exs
Elixir 1.2 Mix introduced a fantastic feature: an ability to share `_build` for in-umbrella applications. It greatly improved development speed.
In order to do that, projects `mix.exs` allows new (or activated) parameters:
```ex
def project do
[
build_path: "../../_build",
config_path: "../../config/config.exs",
]
end
```
This PR introduces support for them, and does a minor consolidation of `_build` path handling.
> Respect paths in project

- lib/mix/tasks/release.ex
When using an umbrella project configuration, `mix` will build an app configuration similar to this:
```elixir
def project do
[app: :app_one,
version: "0.0.1",
build_path: "../../_build",
config_path: "../../config/config.exs",
deps_path: "../../deps",
lockfile: "../../mix.lock",
elixir: "~> 1.0",
deps: deps]
end
```
This results in a shared `_build` folder among all the apps rather than a `_build` folder in each individual app's own folder.
When building a release for an individual app an error is encountered where `exrm` can not find where the app itself has been built when it is using the shared `_build` folder in the root of the umbrella project.  This PR corrects that.
All the tests that run with `mix test` pass when I run them.
> always add build path to lib_dirs

- priv/rel/files/boot
With this change, assuming that we have `hello_cli.ex` in the project `test_cli` with following content:
```ex
defmodule HelloCli do
@spec main() :: no_return
def main() do
IO.puts "HelloCli.main() is running"
:init.get_plain_arguments()
|> Enum.map(&String.Chars.to_string/1)
|> Enum.each(&IO.puts/1)
System.halt(4)
end
end
```
We can release it, and then run 
```bash
bin/test_cli command Elixir.HelloCli main foo bar baz
```
The command above prints:
```
Using /home/vadim/moz/ex/test/rel/test/releases/0.0.1/test.sh
HelloCli.main() is running
foo
bar
baz
```
> modify `priv/rel/files/boot` so it can run elixir in command-line mode.

- README.md
`HTTPS` to hexdocs results in one of those scary _Your connection is not private_ warning messages.
> Fix the link to the documentation.

- priv/rel/files/boot_shim
Title says it all. This fix makes it possible to create a symlink to boot_shim.
> make boot_shim work when there is a symlink to it

- lib/exrm/utils/logger.ex
In mix.exs, exrm declares it supports `elixir ~> 1.0`. However compilation fails on elixir 1.0.4 due to ambiguous expressions.
This fixes it by adding parentheses where appropriate and ambiguous.
> Add parantheses to exrm/utils/logger

- priv/rel/files/boot
This change makes "command" more useful: it can now be used to do things
like changing the OTP app's running environment and so on. If it is
necessary for the OTP app to run, this is easily achievable by calling
Application.ensure_all_started.
> Don't start the OTP app when the boot command "command" is executed

- lib/exrm/plugin.ex
- lib/mix/tasks/release.ex
As part of the compile process for applications and dependencies, it is possible that these apps will create build assets in the `Mix.Project.build_path`. These assets should not be included as part of the process of creating a release, only the contents of the  `#{Mix.Project.build_path}/lib` dir should. As per a conversation with @josevalim. I am open to discussing this a little further to prevent any situations where this would actually produce a breaking change, but I am under the assumption that it would not.
> Limit lib to build_path/lib

- priv/rel/files/boot
Trivial patch, helps diagnostics when EXRM_BOOT_TRACE="anything" is set.
> boot: Add support for tracing init script

- priv/rel/files/boot
Current logic around conform and `vm.args` assumes that `vm.args` will be created by conform. However, current conform does not create vm.args.
This trivial PR fixes this.
> boot: conform does not create vm.args so install unconditionally

- lib/mix/tasks/release.ex
Fixed a small typo in lib/mix/tasks/release.ex.
Removed "to" from the output below:
The following apps should ~~to~~ be added to :applications in mix.exs:
> Fix small typo in output message

- mix.exs
It looks like the main docs page is https://hexdocs.pm/exrm/getting-started.html
But going to the index page on hexdocs takes you to https://hexdocs.pm/exrm/extra-getting-started.html (which doesn't exist)
> Fix broken docs main

- priv/rel/files/boot
Allows installed node ping other nodes in an OTP cluster.
~
Use case: we have an application running over a cluster, with different roles. Nodes of role B should not come up unless they can ping a node of role A. It is valuable to use nodetool (from the release) to try ping a peer as part of the controlling init script.
> boot: add pingpeer command

- priv/rel/files/boot
As per #367, this is a patch that removes invoking vm.args when running the `bin/release command` command. VM args are generally for the actual running process, and reusing `sname` may cause issues when running commands on a server with a running node.
> Remove VMARGS_FILE from "command" release command

- lib/mix/tasks/release.ex
- test/utils_test.exs
I just added a File.chmod to set the permissions to 0o0600 on sys.config and a test to check that it was set. Let me know if you'd like to see something else.  Fixes #380
> set the permissions to 0o0600 on sys.config

- lib/exrm/utils/logger.ex
When running `mix release` non-interactively, for example as part of a script,
we should not see color codes mixed with the output. This can be tested by
piping the output of mix.release. E.g.:
```
mix release
mix release | cat
```
> Strip ANSI color codes in non-TTY mode

- priv/rel/files/boot
Hello.
I've found out that with `RELX_REPLACE_OS_VARS=true` exrm generates invalid runtime configuration files if ENV variables contain slashes.
In our case we've experienced application crash with error
```
could not start kernel pid (application_controller) (error in config file "/app/rel/application/running-config/sys.config.2.config" (none): no ending <dot> found)
```
because one of envirionment variables ended with slash.
> Escape slashes before config file generation

- priv/rel/files/boot.bat
These two very small bugs cause the Windows release bat files to fail to start the node properly, which means you can't even ping it. The bug causing this is a simple error in the bat file where an options string variable is initialised to "" rather than to nothing.
Then once that was fixed, and the node was being started up as e.g. blah@127.0.0.1 and with cookie blah, then another problem still was preventing the upgrade from working, because the erlscript that was supposed to do the work was expecting an extra parameter than what was being sent to it.
boot.bat was initialising conform_opts to "", as if that was an empty string, but in a bat file its not:
@set conform_opts=""
This code was failing:
:install
@if "" == "%2" (
:: Install the service
set args=%erl_opts% %conform_opts% …
> release upgrade was not working for Windows due to simple problems in bat file
